name: Build Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Android Platform Tools
        run: |
          mkdir build
          curl --progress-bar -L  https://googledownloads.cn/android/repository/platform-tools-latest-windows.zip -o build\platform.zip
          tar -xf "build\platform.zip" -C "build\bin" --strip-components=1

      - name: Other work
        run: |
          del build\platform.zip
          del build\lzma.7z
          copy PC-Toolbox.ps1 build\PC-Toolbox.ps1
          copy UseCustomPS.bat build\UseCustomPS.bat

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PC-Toolbox
          path: build\
          compression-level: 7