name: CD Build PC-Toolbox
on:
  workflow_dispatch:
    inputs:
      VERSION:
        type: string
        description: "版本"
        required: true
        default: ""

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Module
        run: |
          Install-Module -Name 7Zip4Powershell -Scope CurrentUser -Force -AllowClobber

      - name: Download Android Platform Tools
        run: |
          mkdir build
          Invoke-WebRequest -Uri https://googledownloads.cn/android/repository/platform-tools-latest-windows.zip -OutFile build\platform.zip
          Expand-7Zip -ArchiveFileName "build\platform.zip" -TargetPath "build\bin"

      - name: Other work
        run: |
          Remove-Item build\platform.zip
          Copy-Item -Path PC-Toolbox.ps1 -Destination build\PC-Toolbox.ps1
          Copy-Item -Path UseCustomPS.bat -Destination build\UseCustomPS.bat
          Move-Item -Path build\bin\platform-tools\* -Destination build\bin\

      - name: Update Version
        run: |
          $version = "${{ github.event.inputs.VERSION }}"
          (Get-Content -Path "build\PC-Toolbox.ps1" -Raw) -replace '\$Version = "CUSTOMER"', "`$Version = `"$version`"" | Set-Content -Path "build\PC-Toolbox.ps1"

      - name: Pack PC-Toolbox for Release
        run: |
          Compress-Archive -Path build\* -DestinationPath PC-Toolbox.zip.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PC-Toolbox
          path: build\
          compression-level: 7

      - name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.parse_version.outputs.VERSION }}
          artifacts: |
            build\PC-Toolbox.zip
          allowUpdates: true
          replacesArtifacts: true