name: Build CI PC-Toolbox
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Module
        run: |
          Install-Module -Name 7Zip4Powershell -Scope CurrentUser -Force -AllowClobber

      - name: Download Android Platform Tools
        run: |
          mkdir build
          Invoke-WebRequest -Uri https://googledownloads.cn/android/repository/platform-tools-latest-windows.zip -OutFile build\platform.zip
          Expand-7Zip -ArchiveFileName "build\platform.zip" -TargetPath "build\bin"

      - name: Other work
        run: |
          Remove-Item build\platform.zip
          Copy-Item -Path PC-Toolbox.ps1 -Destination build\PC-Toolbox.ps1
          Copy-Item -Path UseCustomPS.bat -Destination build\UseCustomPS.bat
          Move-Item -Path build\bin\platform-tools\* -Destination build\bin\

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PC-Toolbox
          path: build\
          compression-level: 7