name: Update Modules
on:
  workflow_dispatch:

jobs:
  fetch-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Environment
        run: |
          sudo apt install zip
          
      - name: Update Tricky-Store
        run: |
          gh release download --latest --repo actions/checkout --pattern 'Tricky-Store*.zip'
          for file in Tricky-Store*.zip; do
            mv "$file" "Update/pctoolbox/TrickyStore.zip"
          done

      - name: Update Zygisk-Next
        run: |
          gh release download --latest --repo actions/checkout --pattern 'Zygisk-Next*.zip'
          for file in Zygisk-Next*.zip; do
            mv "$file" "Update/pctoolbox/Zygisk_Modules/Zygisk-Next.zip"
          done

      - name: Update SuSFS
        run: |
          gh release download --latest --repo actions/checkout --pattern 'ksu_module_susfs*.zip'
          for file in ksu_module_susfs*.zip; do
            mv "$file" "Update/pctoolbox/SuSFS-1.5.2+.zip"
          done

      - name: Update LSPosed (JingMatrix)
        run: |
          gh release download --latest --repo actions/checkout --pattern 'LSPosed*release.zip'
          for file in LSPosed*.zip; do
            mv "$file" "Update/pctoolbox/LSPosed.zip"
          done

      - name: Pack Modules ZIP
        run: |
          cp Files/customize.sh Update/customize.sh
          cp Files/module.prop Update/module.prop
          zip -r Modules.zip Update/

      - name: 上传目录
        uses: actions/upload-artifact@v7
        with:
          name: Modules.zip
          path: Update/Modules.zip
          

      - name: Commit and push files
        run: |
          cp Update/Modules.zip Files/Modules.zip
          git add Files/Modules.zip
          git diff --cached --quiet || git commit -m "chore: update Modules.zip in Files directory [skip ci]"
          git push origin HEAD:${{ github.ref_name }}